version: "1"
services:
  app:
    build: ./docker
    image: juanignaso/notes_app
    ports:
      - "8080:80"
    volumes:
    #con esto el directorio actual, el cual esta la app se va a
    #montar dentro de '/var/www'
      - ./:/var/www
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DataBaseScript/dbScript.sql:/docker-entrypoint-initdb.d/init.sql   
    environment:
      MYSQL_ROOT_PASSWORD: 1234abc.
      MYSQL_DATABASE: Notes_App_DB
      MYSQL_USER: usertest
      MYSQL_PASSWORD: 1234abc.

volumes:
  mysql-data: